version: "3"

services: 

  elasticsearch:
    image: elasticsearch:5.6.10
    networks: 
      - net

  logstash:
    build: ./logstash
    depends_on: 
      - elasticsearch
    ports:
      - 12201:12201/udp
      - 53:53
    networks:
      - net

  kibana:
    image: kibana:5.6.10
    depends_on:
      - elasticsearch
    ports: 
      - 5601:5601
    networks: 
      - net

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    depends_on:
      - logstash
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"

networks: 

  net:
    driver: bridge
